## 파이토치(PyTorch) 프레임워크란?
- 파이토치(PyTorch)는 메타에서 개발한 파이썬 기반 오픈소스 딥러닝 프레임워크로, GPU 병렬 연산과 자동 미분 기능을 제공합니다.  
실행 시점에 그래프가 결정되는 동적 계산 방식을 채택해 복잡한 조건문과 반복문 구조도 제약 없이 유연하게 처리할 수 있습니다.  
파이썬 고유의 직관적인 코드 작성 방식을 지원하므로 디버깅과 수정이 용이하며 전체적인 모델 연구 및 개발 속도를 획기적으로 줄여줍니다.

- 즉, 머신러닝 딥러닝을 만들 수 있는 개발 환경입니다. 현업 파이토치8: 텐서플로우2


[파이토치 공식문서](https://docs.pytorch.org/docs/2.14/index.html)

# 1. 스칼라(Scalar)
- 스칼라는 정수나 실수처럼 단 하나의 숫자만을 표현하는 가장 기본적인 자료형이다.
  파이토치에서는 이 스칼라를 차원이 존재하지 않는 0차원 텐서 형태로 다룬다.

In [1]:
import torch
import numpy as np

In [2]:
num1 = torch.tensor(10)
num2 = torch.tensor(1.5)
print(num1)
print(num2)
print(type(num1))
print(type(num2))

tensor(10)
tensor(1.5000)
<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [8]:
# s = torch.tensor("단비")
# print(s) -> 오류(tensor 자료형에는 숫자형만 들어올 수 있음)

### 모델은 컴퓨터를 학습시키는 것을 의미하며, 학습은 모두 숫자형으로만 가능하다. 즉 tensor는 숫자 자료형밖에 넣을 수 없다.

In [4]:
num3 = torch.tensor([10], dtype=torch.float64)
print(num3)

tensor([10.], dtype=torch.float64)


In [5]:
num4 = torch.tensor([20], dtype=torch.int64)
print(num4)

tensor([20])


In [6]:
num5 = torch.tensor([20], dtype=torch.long)
print(num4)

tensor([20])


In [7]:
num6 = torch.tensor([[60]])
print(num6)

tensor([[60]])


In [9]:
num3 + 10

tensor([20.], dtype=torch.float64)

In [10]:
num1 + 10

tensor(20)

## .item()
- 텐서 자료형에서 값을 꺼내오는 메서드

In [16]:
num3.item()

10.0

In [17]:
print(num1)
print(num2)

print(num1 + num2)

tensor(10)
tensor(1.5000)
tensor(11.5000)


In [20]:
print(num1)
print(num3)

print(num1 + num3)  # 0차원 스칼라 + 1차원 스칼라 = 1차원 스칼라

tensor(10)
tensor([10.], dtype=torch.float64)
tensor([20.], dtype=torch.float64)


In [22]:
print(num1, num6)
print(num1 + num6)  # 0차원 스칼라 + 2차원 스칼라 = 2차원 스칼라

tensor(10) tensor([[60]])
tensor([[70]])


### 0차원 값과 다차원 값을 연사하면 다차원 값으로 반환한다. ex) 0차원 + 2차원 = 2차원

## 2) 벡터(Vector)
- 하나 이상의 원소가 일렬로 나열된 1차원 텐서 형태의 자료구조를 의미한다.
- 파이토치에서는 n의 원소가 담긴 벡터는 (n, )형태의 차원을 갖게 된다.

In [23]:
v1 = torch.tensor([1.0,2.0,3.0])
v2 = torch.tensor([10.0,20.0,30.0])

In [24]:
print(v2.shape)
print(v2.size())

torch.Size([3])
torch.Size([3])


In [25]:
print(num1 + v1)
print(v1 + v2)

tensor([11., 12., 13.])
tensor([11., 22., 33.])


## 행렬(Matrix)
- 행과 열로 이루어진 2차원 형태의 텐서를 의미한다. 예를 들어 2행 2열의 데이터라면 torch.tensor([[1,2],[3,4]])로 표기되며  
  행렬곱 연산이 가능하다. 파이토치에서 행렬 연산은 torch.mm 함수(np.matmul() 함수와 동일)나 @ 연산자로 간편하게 수행할 수 있습니다.

In [26]:
mt1 = torch.tensor([[1,2],[3,4]])
mt2 = torch.tensor([[10,20],[30,40]])

print(mt1)
print(type(mt1))
print(mt1.shape)

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
torch.Size([2, 2])


In [27]:
print(mt1 + num1)
print(mt1 + mt2)

tensor([[11, 12],
        [13, 14]])
tensor([[11, 22],
        [33, 44]])


In [30]:
# print(mt1 + v1) -> error(열의 개수가 다르므로 연산 불가)

In [32]:
print(mt1 + torch.tensor([100,200]))  # 열의 개수만 똑같으면 차원이 달라도 연산 가능

tensor([[101, 202],
        [103, 204]])


## 4) 텐서

In [33]:
data = [
    [1,2],
    [3,4]
]

t1 = torch.tensor(data)
print(t1)

tensor([[1, 2],
        [3, 4]])


In [35]:
[1,2] + [3,4]
# -> 브로드캐스팅 연산 안됨. tensor로 바꿔서 연산해야 브로드캐스팅 가능

[1, 2, 3, 4]

## tensor -> ndarray

In [36]:
print(t1)
print(type(t1))
print(t1.numpy())
print(type(t1.numpy()))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


## ndarray -> tensor

In [39]:
ndarray1 = np.array([10,20,30])
ndarray1

print(torch.from_numpy(ndarray1))
print(ndarray1)

tensor([10, 20, 30])
[10 20 30]


In [43]:
t3 = torch.tensor([
    [1,2,3,4],
    [10,20,30,40],
    [5,6,7,8]
])

print(t3)
print(t3[1])
# 인덱싱 가능

tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40],
        [ 5,  6,  7,  8]])
tensor([10, 20, 30, 40])


In [48]:
print(t3[1:2])
# 슬라이싱도 가능

tensor([[10, 20, 30, 40]])


In [51]:
print(t3[:, 0])
print(t3[...,0])
# 모든 행의 마지막 열의 0번째 값을 가져옴

tensor([ 1, 10,  5])
tensor([ 1, 10,  5])


In [55]:
t4 = np.arange(1,13).reshape(2,2,3)
t4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
t5 = torch.from_numpy(t4)
t5

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [58]:
print(t5[:, 0])
print(t5[..., 0])

tensor([[1, 2, 3],
        [7, 8, 9]])
tensor([[ 1,  4],
        [ 7, 10]])


## 5) 행렬곱
## 내적(Dot Product) 계산 및 개념

### 개념
- 내적은 두 벡터 간의 원소별 곱을 모두 더하는 연산으로, 두 벡터가 얼마나 같은 방향을 향하는지 나타내는 유사도(방향성 일치도)의 척도입니다.

### 내적 공식
- 3차원 벡터 A = (x1, y1, z1)와 B = (x2, y2, z2)의 내적 공식은 다음과 같습니다.

A · B = x1*x2 + y1*y2 + z1*z3

- 첫 번째 성분끼리 곱하기: 1 x 11 = 11
- 두 번째 성분끼리 곱하기: 2 x 12 = 24
- 세 번째 성분끼리 곱하기: 3 x 13 = 39
- 최종 내적 값: 11 + 24 + 39 = 74 (0차원 스칼라)

### 내적과 행렬곱의 관계
- 1차원, 2차원, 3차원 텐서 모두 행렬곱 연산이 가능하며, 행렬곱의 결과 형태(Shape)는 입력되는 행렬들의 크기에 따라 다르게 결정됩니다.  
행렬곱을 이루는 각 위치의 원소를 계산하는 본질적인 연산 방식이 바로 벡터의 내적이며, (1, n) 행렬과 (n, 1) 행렬의 곱처럼  
결과가 1x1 형태의 2차원 행렬로 나오는 경우 그 내부 원소 값은 두 벡터의 내적 값(0차원 스칼라)과 동일합니다.  

In [61]:
v1 = torch.tensor([1,2,3])
v2 = torch.tensor([1,2,3])

print(v1, v2)

tensor([1, 2, 3]) tensor([1, 2, 3])


In [62]:
print(torch.matmul(v1, v2))

tensor(14)


In [63]:
"""
    1차원 벡터 내적 [1, 2, 3] x [1, 2, 3]
    (3,) 크기를 가지는 1차원 벡터 2개의 내적 연산 과정입니다.

    - 첫 번째 성분끼리 곱하기: 1 x 1 = 1
    - 두 번째 성분끼리 곱하기: 2 x 2 = 4
    - 세 번째 성분끼리 곱하기: 3 x 3 = 9
    - 최종 연산 결과: 1 + 4 + 9 = 14
"""

None

In [65]:
v3 = torch.tensor([[1,2,3]])
v4 = torch.tensor([[1],[2],[3]])

print(v3)
print(v4)

print(v3.shape)
print(v4.shape)

tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])
torch.Size([1, 3])
torch.Size([3, 1])


In [66]:
print(torch.mm(v3,v4))

tensor([[14]])


In [67]:
m3 = torch.tensor([[1,2],[3,4]])
m4 = torch.tensor([[5,6],[7,8]])

print(m3)
print(m4)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])


In [69]:
print(torch.mm(m3,m4))
"""
    2x2 행렬곱 [[1, 2], [3, 4]] x [[5, 6],
                                 [7, 8]]

    - 첫 번째 행 × 첫 번째 열:
      1 x 5 + 2 x 7 = 19

    - 첫 번째 행 × 두 번째 열:
      1 x 6 + 2 x 8 = 22

    - 두 번째 행 × 첫 번째 열:
      3 x 5 + 4 x 7 = 43

    - 두 번째 행 × 두 번째 열:
      3 x 6 + 4 x 8 = 50

    - 최종 연산 결과:
      [[19, 22], [43, 50]]

      내적이 클수록 → 같은 방향에 가까움
      내적이 작을수록 → 같은 반대에 가까움
"""

None

tensor([[19, 22],
        [43, 50]])


### 참고. 유클리드 거리 (Euclidean Distance)
- 두 벡터 `A`, `B` 사이의 거리를 구하는 공식입니다.
- 유클리드 거리 = 각 차이를 제곱 → 전부 더하기 → 제곱근

$$
d(A,B) = \sqrt{\sum_{i=1}^{n}(A_i-B_i)^2}
$$

2차원 벡터라면:

$$
d(A,B) = \sqrt{(A_1-B_1)^2+(A_2-B_2)^2}
$$

예시:

$$
A=(1,2), \quad B=(3,4)
$$

$$
d(A,B)
= \sqrt{(1-3)^2+(2-4)^2}
$$

$$
= \sqrt{(-2)^2+(-2)^2}
$$

$$
= \sqrt{4+4}
$$

$$
= \sqrt{8}
\approx 2.83
$$

In [ ]:
# torch.norm() : 두 백터 간 거리 구함

In [72]:
a = torch.tensor([1,2], dtype=torch.float32)
b = torch.tensor([3,4], dtype=torch.float32)

diff = a - b
print(diff)

distance = torch.norm(diff)
print(distance)

tensor([-2., -2.])
tensor(2.8284)


## 파이토치의 핵심 장점: GPU 활용과 연산 가속
- GPU(Graphics Processing Unit)는 본래 이미지 렌더링과 같은 대규모 병렬 계산을 처리하기 위해 설계된 그래픽 처리 장치입니다.  
  하지만 최근에는 수많은 행렬 및 벡터 연산이 필요한 인공지능(AI)과 딥러닝 분야에서 뛰어난 연산 가속기로 널리 활용되고 있습니다.  
  GPU는 다수의 코어를 통해 수천, 수만 개의 연산을 동시에 병렬로 처리할 수 있는 구조를 갖추고 있어 딥러닝 모델 학습에 매우 최적화되어 있습니다.
- 파이토치에서 이러한 GPU 가속을 활용하기 위해서는 외장 그래픽카드와 함께 전용 하드웨어 설치 프로그램(예: NVIDIA CUDA 등)을 갖추어야 하며,  
  내장 그래픽 환경에서는 사용이 불가능합니다. 만약 로컬에 적합한 그래픽 카드가 없는 경우, 구글 코랩(Google Colab) 환경을 이용하면  
  무료로 GPU 가속을 사용해 볼 수 있습니다.
- 한편, 머신러닝과 딥러닝 전용으로 개발된 또 다른 가속 장치인 TPU(Tensor Processing Unit)의 경우,  
  본래 텐서플로(TensorFlow) 환경에 최적화되어 있어 파이토치에서는 직접적인 사용 및 적용이 다소 제한적입니다.  
  따라서 파이토치를 활용한 딥러닝 연산 시에는 GPU 환경을 구축하고 사용하는 것이 가장 일반적이고 효율적인 방법입니다.

In [81]:
print("Cuda(Nvidia) 사용 가능 여부 :", torch.cuda.is_available())  # window(외장하드)
print("Mps(Mac) 사용 가능 여부 :", torch.mps.is_available())  # mac
print("Cpu 사용 가능 여부 :", torch.cpu.is_available())  # window(cpu)
print("Xpu(Intel 내장그래픽) 사용 가능 여부 :", torch.xpu.is_available())  # intel 내장그래픽

Cuda(Nvidia) 사용 가능 여부 : False
Mps(Mac) 사용 가능 여부 : False
Cpu 사용 가능 여부 : True
Xpu(Intel 내장그래픽) 사용 가능 여부 : False


In [82]:
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.mps.is_available():
    device = torch.device("mps")
elif torch.xpu.is_available():
    device = torch.device("xpu")
else:
    device = torch.device("cpu")

print(f"현재 선택된 장치: {device}")

현재 선택된 장치: cpu


In [85]:
t1 = torch.tensor([10])
# .to()
t1_gpu = t1.to(device)

print(t1)
print(t1_gpu)

print(t1 + t1_gpu)
# -> 원래는 cpu와 gpu의 영역이 다르기 때문에 연산이 안됨.
# 이 노트북은 외장그래픽이 없어서 똑같이 cpu에 저장되기에 연산 되는 것.

tensor([10])
tensor([10])
tensor([20])


In [86]:
print(t1.is_cpu)
print(t1_gpu.is_cpu)
print(t1_gpu.is_cuda)
print(t1_gpu.is_mps)
print(t1_gpu.is_xpu)

True
True
False
False
False


In [87]:
t2 = torch.tensor([[1,2],[3,4]])
t3 = torch.tensor([[10,20],[30,40]])

t2_gpu = t2.to(device)
t3_gpu = t3.to(device)

In [88]:
print(t2_gpu + t3_gpu)
print(t2_gpu * t3_gpu)
print(t2_gpu - t3_gpu)
print(t2_gpu / t3_gpu)

tensor([[11, 22],
        [33, 44]])
tensor([[ 10,  40],
        [ 90, 160]])
tensor([[ -9, -18],
        [-27, -36]])
tensor([[0.1000, 0.1000],
        [0.1000, 0.1000]])


In [92]:
print(t2_gpu.sum())
print(t2_gpu.sum(dim=0))  # dim=은 axis=과 같은 기능
print(t2_gpu.sum(dim=1))  

tensor(10)
tensor([4, 6])
tensor([3, 7])


In [96]:
# .to() : 자료형도 변경 가능
t4 = t3_gpu.to(torch.float32)
print(t4.mean())
print(t4.mean(dim=0))
print(t4.mean(dim=1))

tensor(25.)
tensor([20., 30.])
tensor([15., 35.])


In [97]:
print(t4.min())
print(t4.max())

tensor(10.)
tensor(40.)


In [102]:
print(t4)
print(t4.argmax())
print(t4.argmin())
print(t4.argmax(dim=0))
print(t4.argmin(dim=0))
print(t4.argmax(dim=1))
print(t4.argmin(dim=1))

tensor([[10., 20.],
        [30., 40.]])
tensor(3)
tensor(0)
tensor([1, 1])
tensor([0, 0])
tensor([1, 1])
tensor([0, 0])


In [103]:
# .flatten() : 평탄화
print(torch.flatten(t4))
torch.flatten(t4).argmax()

tensor([10., 20., 30., 40.])


tensor(3)

## 6) 텐서의 차원 조작

In [106]:
print(torch.tensor(np.arange(1,13).reshape(3,4)))
t1 = torch.from_numpy(np.arange(1,13).reshape(3,4))
t1

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

### .cat() : 기존의 텐서를 연결하는(텐서에 값을 추가하는) 메서드

In [113]:
# torch.cat([t1, [1,2,3]], dim=0) # -> error(연결할 때 리스트는 못들어옴)

In [114]:
torch.cat([t1,t1],dim=0)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [115]:
torch.cat([t1,t1],dim=1)

tensor([[ 1,  2,  3,  4,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  5,  6,  7,  8],
        [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [116]:
v1 = torch.tensor(range(1,5))
v1

tensor([1, 2, 3, 4])

In [117]:
v1[2] = 300
v1

tensor([  1,   2, 300,   4])

In [119]:
v2 = torch.tensor(range(1,5))
# .clone(): 원본 배열과 값을 공유하지 않는(깊은 복사) 복사본을 생성
v3 = v2.clone()  # 깊은 복사
v2

tensor([1, 2, 3, 4])

In [120]:
v3[0] = 1000

print(v2, v3)

tensor([1, 2, 3, 4]) tensor([1000,    2,    3,    4])


In [122]:
v4 = v2
v4[0] = 1000
print(v2, v4)
v2[0] = 1
print(v2, v4)

tensor([1000,    2,    3,    4]) tensor([1000,    2,    3,    4])
tensor([1, 2, 3, 4]) tensor([1, 2, 3, 4])


In [124]:
v2.view(2,2)  # reshape와 비슷한 기능

tensor([[1, 2],
        [3, 4]])

In [141]:
t1 = torch.rand((10,3,4))

print(t1)

tensor([[[0.8354, 0.9429, 0.6016, 0.9171],
         [0.9327, 0.5719, 0.6840, 0.2412],
         [0.0692, 0.6677, 0.4378, 0.5698]],

        [[0.2351, 0.2501, 0.0689, 0.1919],
         [0.3633, 0.6056, 0.6401, 0.1550],
         [0.0431, 0.4485, 0.6978, 0.7320]],

        [[0.3245, 0.0220, 0.9789, 0.9386],
         [0.4140, 0.7729, 0.9261, 0.7985],
         [0.5360, 0.0419, 0.2157, 0.4175]],

        [[0.4186, 0.1580, 0.3479, 0.5300],
         [0.6519, 0.5400, 0.3571, 0.0717],
         [0.4366, 0.4699, 0.0793, 0.7332]],

        [[0.0913, 0.1183, 0.5366, 0.5248],
         [0.9553, 0.5005, 0.9108, 0.3099],
         [0.3298, 0.2361, 0.8197, 0.8435]],

        [[0.4583, 0.6134, 0.5200, 0.4520],
         [0.0224, 0.1066, 0.1388, 0.8641],
         [0.6130, 0.9313, 0.3610, 0.0406]],

        [[0.4068, 0.9149, 0.0372, 0.9464],
         [0.3264, 0.1103, 0.4375, 0.3380],
         [0.4300, 0.4784, 0.2026, 0.0615]],

        [[0.9328, 0.3053, 0.9748, 0.4034],
         [0.9891, 0.2975, 0.2210, 0.5939

In [142]:
print(t1.shape)

torch.Size([10, 3, 4])


### .permute() : 차원 변경

In [143]:
# torch.rand((10,3,4))
t2 = t1.permute(2,1,0)
# -> (4,3,10)
print(t2.shape)
print(t2)

torch.Size([4, 3, 10])
tensor([[[0.8354, 0.2351, 0.3245, 0.4186, 0.0913, 0.4583, 0.4068, 0.9328,
          0.6195, 0.3801],
         [0.9327, 0.3633, 0.4140, 0.6519, 0.9553, 0.0224, 0.3264, 0.9891,
          0.7865, 0.0638],
         [0.0692, 0.0431, 0.5360, 0.4366, 0.3298, 0.6130, 0.4300, 0.5095,
          0.3917, 0.6537]],

        [[0.9429, 0.2501, 0.0220, 0.1580, 0.1183, 0.6134, 0.9149, 0.3053,
          0.7308, 0.2911],
         [0.5719, 0.6056, 0.7729, 0.5400, 0.5005, 0.1066, 0.1103, 0.2975,
          0.2270, 0.9462],
         [0.6677, 0.4485, 0.0419, 0.4699, 0.2361, 0.9313, 0.4784, 0.9103,
          0.2572, 0.6217]],

        [[0.6016, 0.0689, 0.9789, 0.3479, 0.5366, 0.5200, 0.0372, 0.9748,
          0.0024, 0.8264],
         [0.6840, 0.6401, 0.9261, 0.3571, 0.9108, 0.1388, 0.4375, 0.2210,
          0.1024, 0.6830],
         [0.4378, 0.6978, 0.2157, 0.0793, 0.8197, 0.3610, 0.2026, 0.7930,
          0.7765, 0.0754]],

        [[0.9171, 0.1919, 0.9386, 0.5300, 0.5248, 0.4520, 0.94

In [134]:
t3 = torch.randint(low=0, high=10, size=(10,3,4))
t3

tensor([[[1, 0, 4, 2],
         [2, 3, 1, 9],
         [4, 0, 8, 7]],

        [[9, 4, 6, 0],
         [4, 3, 1, 8],
         [1, 6, 1, 8]],

        [[1, 3, 5, 0],
         [5, 9, 9, 3],
         [7, 5, 9, 4]],

        [[7, 5, 9, 7],
         [2, 3, 0, 8],
         [1, 4, 1, 1]],

        [[5, 1, 6, 2],
         [5, 0, 7, 7],
         [0, 0, 7, 8]],

        [[4, 2, 5, 6],
         [5, 0, 7, 8],
         [0, 3, 5, 5]],

        [[9, 7, 2, 1],
         [2, 0, 0, 8],
         [7, 1, 1, 2]],

        [[2, 5, 2, 5],
         [6, 2, 2, 4],
         [7, 8, 1, 6]],

        [[8, 3, 6, 6],
         [2, 0, 0, 5],
         [3, 1, 9, 1]],

        [[6, 1, 3, 3],
         [9, 0, 3, 6],
         [8, 2, 5, 7]]])

In [137]:
# 차원 추가
t4 = t3.unsqueeze(0)
print(t3.shape)
print(t4.shape)

torch.Size([10, 3, 4])
torch.Size([1, 10, 3, 4])


In [139]:
t5 = t4.squeeze()
print(t5.squeeze())

tensor([[[1, 0, 4, 2],
         [2, 3, 1, 9],
         [4, 0, 8, 7]],

        [[9, 4, 6, 0],
         [4, 3, 1, 8],
         [1, 6, 1, 8]],

        [[1, 3, 5, 0],
         [5, 9, 9, 3],
         [7, 5, 9, 4]],

        [[7, 5, 9, 7],
         [2, 3, 0, 8],
         [1, 4, 1, 1]],

        [[5, 1, 6, 2],
         [5, 0, 7, 7],
         [0, 0, 7, 8]],

        [[4, 2, 5, 6],
         [5, 0, 7, 8],
         [0, 3, 5, 5]],

        [[9, 7, 2, 1],
         [2, 0, 0, 8],
         [7, 1, 1, 2]],

        [[2, 5, 2, 5],
         [6, 2, 2, 4],
         [7, 8, 1, 6]],

        [[8, 3, 6, 6],
         [2, 0, 0, 5],
         [3, 1, 9, 1]],

        [[6, 1, 3, 3],
         [9, 0, 3, 6],
         [8, 2, 5, 7]]])


## 자동 미분과 기울기(requires_grad)
### 미분
- 어떤 값(변수)이 아주 조금 바뀔 때, 그에 따라 다른 값이 얼마나 변하는 지 계산하는 방법이다.

$$
\frac{\Delta y}{\Delta x}
$$

이는 x가 변한 만큼 y가 얼마나 변했는지를 나타냅니다.

예를 들어:

$$
x: 2 \rightarrow 3
$$

이면

$$
\Delta x = 1
$$

그리고

$$
y: 4 \rightarrow 7
$$

이면

$$
\Delta y = 3
$$

따라서

$$
\frac{\Delta y}{\Delta x}
=
\frac{3}{1}
=
3
$$

이것을 평균 변화율이라고 합니다.

미분은 변화량을 0에 가깝게 줄였을 때의 변화율을 의미합니다.

$$
\frac{dy}{dx}
=
\lim_{\Delta x \rightarrow 0}
\frac{\Delta y}{\Delta x}
$$

## 순전파 (Forward Pass): out 계산
### 1) 입력 벡터 정의
$$x = [x_1, x_2] = [3.0, 4.0]$$
$$y = [y_1, y_2] = [1.0, 2.0]$$

### 2) z = x + y 연산
각 성분별로 더해져 새로운 2차원 벡터 $z$가 생성됩니다.
$$z_1 = x_1 + y_1 = 3.0 + 1.0 = 4.0$$
$$z_2 = x_2 + y_2 = 4.0 + 2.0 = 6.0$$
$$z = [4.0, 6.0]$$

### 3) out = z.mean() 연산
벡터 $z$의 모든 성분을 더한 뒤 성분의 개수($n=2$)로 나누어 평균을 구합니다.
$$out = \frac{z_1 + z_2}{2} = \frac{4.0 + 6.0}{2} = 5.0$$

## 2. 역전파 (Backward Pass): 미분 계산

`out.backward()`가 호출되면 연쇄 법칙(Chain Rule)에 의해 최종 출력($out$)에 대한 각 입력 성분들의 미분 값(기울기)이 역순으로 계산됩니다.

### 1) out에 대한 z의 편미분
$$out = \frac{1}{2}z_1 + \frac{1}{2}z_2$$
$$\frac{\partial out}{\partial z_1} = 0.5, \quad \frac{\partial out}{\partial z_2} = 0.5$$

### 2) 연쇄 법칙을 통한 최종 미분 계산 (x와 y 기준)
$z_1 = x_1 + y_1$ 이므로 $\frac{\partial z_1}{\partial x_1} = 1$ 입니다. 이를 활용해 최종 미분 값을 구합니다.

* **x에 대한 미분 값:**
  $$\frac{\partial out}{\partial x_1} = \frac{\partial out}{\partial z_1} \times \frac{\partial z_1}{\partial x_1} = 0.5 \times 1 = 0.5$$
  $$\frac{\partial out}{\partial x_2} = \frac{\partial out}{\partial z_2} \times \frac{\partial z_2}{\partial x_2} = 0.5 \times 1 = 0.5$$

* **y에 대한 미분 값 (위와 동일):**
  $$\frac{\partial out}{\partial y_1} = 0.5, \quad \frac{\partial out}{\partial y_2} = 0.5$$

In [148]:
x = torch.tensor([3.0,4.0], requires_grad=True)
y = torch.tensor([1.0,2.0], requires_grad=True)

print(x, y)
print(x + y)

out = (x + y).mean()  # 순전파
print(out)

tensor([3., 4.], requires_grad=True) tensor([1., 2.], requires_grad=True)
tensor([4., 6.], grad_fn=<AddBackward0>)
tensor(5., grad_fn=<MeanBackward0>)


In [149]:
out.backward()  # 역전파(!중요!)

In [151]:
print(f"x.grad : {x.grad}")
print(f"y.grad : {y.grad}")

# 가중치 구하기

x.grad : tensor([0.5000, 0.5000])
y.grad : tensor([0.5000, 0.5000])
